package:
  name: scikit-time-dev
  # version number: [base tag]+[commits-upstream]_[git_hash]
  # eg. v2.0+0_g8824162
  version: {{ GIT_DESCRIBE_TAG[1:] + '+' + GIT_BUILD_STR}}
source:
  path: ../..
  # borked, but preferable, because it creates a "clean" working copy locally.
  #git_url: ../../

build:
  script_env:
   - CIRCLE_TEST_REPORTS
   - OMP_NUM_THREADS
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - cython
    # actually we could build with np18, but fastcluster (dep of mdtraj, we link against) is only avail for 1.9
    - numpy 1.9.*  # [not (win and (py35 or py36))]
    - numpy 1.9.*  # [win and py35]
    - numpy 1.11.*  # [win and py36]
    - python
    - scipy
    - setuptools
    - toolchain

  run:
    - numpy >=1.9,<1.14  # [not (win and (py35 or py36))]
    - numpy >=1.9,<1.14  # [win and py35]
    - numpy >=1.11,<1.14 # [win and py36]
    - python
    - scipy
    - setuptools
    - six >=1.10
    # - tqdm

test:
  source_files:
    #- conftest.py
    - setup.cfg
  requires:
    - pytest
    - pytest-cov
    - coverage
   # TODO: disabled on win64, until https://bugs.python.org/issue31701 is fixed.
    - pytest-faulthandler # [not win]
    - pytest-xdist
    - scikit-learn
    # https://github.com/Frozenball/pytest-sugar/issues/124
    #- pytest-sugar
