package:
  name: pyemma-dev
  # version number: [base tag]+[commits-upstream]_[git_hash]
  # eg. v2.0+0_g8824162
  version: {{ GIT_DESCRIBE_TAG[1:] + '+' + GIT_BUILD_STR}}
source:
  path: ../..
  # borked, but preferable, because it creates a "clean" working copy locally.
  #git_url: ../../

build:
  preserve_egg_dir: True
  script_env:
   - CIRCLE_TEST_REPORTS
   - OMP_NUM_THREADS
   - PYEMMA_NJOBS
  script: python -B setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - cython
    - gcc # [linux or osx]
    - mdtraj
    - numpy x.x
    - pybind11
    - python >=3
    - scipy
    - setuptools
  run:
    - bhmm >=0.6,<0.7
    - decorator >=4.0.0
    - libgcc # [linux or osx]
    - matplotlib
    - mdtraj
    - msmtools >=1.2
    - numpy x.x
    - pathos
    - psutil >3.1
    - python >=3
    - pyyaml
    - scipy
    - setuptools
    - thermotools >=0.2.6
    - tqdm

test:
  source_files:
    - conftest.py
    - setup.cfg
  files:
    - matplotlibrc
  requires:
    - h5py
    - pytest
    - pytest-cov
   # TODO: disabled on win64, until https://bugs.python.org/issue31701 is fixed.
    - pytest-faulthandler # [not win]
    - pytest-xdist
    # https://github.com/Frozenball/pytest-sugar/issues/124
    #- pytest-sugar

about:
  home: http://emma-project.org
  license: GNU Lesser Public License v3+
  summary: "EMMA: Emma's Markov Model Algorithms"
